name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (deep)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Analyze
        run: pnpm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (deep)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm exec nx run-many -t test --coverage

      - name: Collect coverage
        run: echo "COVERAGE=$(node .github/scripts/list-coverage-files.js)" >> $GITHUB_ENV

      - name: Report coverage
        uses: coverallsapp/github-action@v2
        with:
          files: ${{ env.COVERAGE }}

  e2e:
    name: End-to-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (deep)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Install browsers
        run: pnpm exec playwright install --with-deps

      - name: Run end-to-end tests
        run: pnpm exec nx run-many -t e2e

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (deep)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Check Format
        run: pnpm exec prettier --check .

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (deep)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm run type-check
