name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (deep)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Setup Bun 1.x
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1

      - name: Authenticate NPM
        run: npm config set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Publish versions
        run: pnpm nx release publish

      - name: Create Release Pull Request
        run: node .github/scripts/create-versioning-pull-request.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_HEAD_BRANCH: "automated-versioning"
          GITHUB_BASE_BRANCH: "main"
